services:
  - type: web
    name: brightpath-academy-app
    env: python
    buildCommand: pip install -r Dash_App/requirements.txt
    startCommand: gunicorn Dash_App.CreditRisk:server
    plan: free
